spring.application.name=expenses
spring.data.mongodb.uri=${MONGO_URI}
server.port=8082

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.web.filter=DEBUG

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=expenses-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
